Имплементация IPoint с событием об изменении координат - изменено название PointCoordinatesChangedEventArgs.
zykindmitry/SchemeExpert pull request #7
Opened 2019-12-04 11:43 UTC by afdenisoff-dev

2019-12-04 12:07 UTC, zykindmitry requested changes

2019-12-04 12:07 UTC, zykindmitry commented on DevFactoryZ.SchemeExpert/Volume/IPoint.cs
> +        double PreviousZ { get; }
1. Не реализует пункт 3 задания (подписка на событие изменения координат через интерфейс)
2. Пункт 3.2 задания реализован избыточно. Время жизни данных о предыдущем состоянии точки больше, чем это требуется (после того как событие обработано эти значения уже не нужны), кроме того если точка не меняла свое состояния после создания, то значения Previous* будут некорректными

2019-12-04 12:07 UTC, zykindmitry commented on DevFactoryZ.SchemeExpert/Infrastructure/PointCoordinatesChangedEventArgs.cs
> +        public PointCoordinatesChangedEventArgs(IPoint point)
Использовать IPoint пока можно, но когда будет исправлено замечания по п.3, то он перестанет подходить в качестве аргумента события. 
Рекомендую обсудить с Андреем (он уже заканчивает похожую задачу, только для 2D)

2019-12-04 12:07 UTC, zykindmitry commented on DevFactoryZ.SchemeExpert/Volume/Point.cs
> +            if (!PreviousX.Equals(newValueX) || !PreviousY.Equals(newValueY) || !PreviousZ.Equals(newValueZ))
Вот тут есть подвох. Из-за округлений и плавающей точки даже если вы передадите нули, то равенство не гарантируется. 
https://docs.microsoft.com/ru-ru/dotnet/api/system.double.equals?view=netframework-4.8
Я предлагаю решать эту проблему тем, что реализовать метод расширения (создать в корне проекта статический класс DoubleExtensions ) и в нем реализовать ряд методов по сравнению double с использованием precision. Т.е. 2 числа double равны, если модуль и разницы меньше либо равен 10 в степени - precision

2019-12-04 12:07 UTC, zykindmitry commented on DevFactoryZ.SchemeExpert/Volume/Point.cs
> +            if (!PreviousX.Equals(newValueX) || !PreviousY.Equals(newValueY) || !PreviousZ.Equals(newValueZ))
Precision закрыто хранить в самом объекте и принимать в конструкторе, наружу не выставлять и не позволять изменять

2019-12-04 12:07 UTC, zykindmitry commented on DevFactoryZ.SchemeExpert/Volume/Point.cs
> +            temp?.Invoke(this, new PointCoordinatesChangedEventArgs(point));
?.Invoke уже потокобезопасный с версии c# 6.0, в переменной temp нет нужды

2019-12-04 12:56 UTC, afdenisoff-dev commented on DevFactoryZ.SchemeExpert/Volume/IPoint.cs
> +        double PreviousZ { get; }
1. Т.е. надо еще определить event в интерфейсе IPoint? 
2. Т.е. свойства PreviewX,Y,Z - не нужны, достаточно локальных переменных в методе MoveTo?
Насчет некорректности (хотя и неактуально): если точка не переезжала, то предыдущие координаты совпадают с текущими. В чем некорректность?

2019-12-04 13:11 UTC, afdenisoff-dev commented on DevFactoryZ.SchemeExpert/Infrastructure/PointCoordinatesChangedEventArgs.cs
> +        public PointCoordinatesChangedEventArgs(IPoint point)
Я сначала сделал нечто подобное - еще один тип для передачи событию, но решил, что можно обойтись типом Point, добавив свойства предыдущих значений координат. 
Кстати, у Андрея аргумент события реализован не полностью - нет предыдущих значений (или новых, смотря что он помещает в аргумент). И namespace все-таки какой - volume и plane или 3D и 2D?

2019-12-04 13:25 UTC, zykindmitry commented on DevFactoryZ.SchemeExpert/Infrastructure/PointCoordinatesChangedEventArgs.cs
> +        public PointCoordinatesChangedEventArgs(IPoint point)
1) namespace _2D, _3D
2) То, что у Андрея нет предыдущих значений, это я конечно я упустил

2019-12-04 13:28 UTC, zykindmitry commented on DevFactoryZ.SchemeExpert/Volume/IPoint.cs
> +        double PreviousZ { get; }
1. Все верно
2. Да, мы зафиксируем старые значения координат внутри метода MoveTo и прочих и передадим их в исключительно в качестве аргументов события

var point = new Point(1,1,1); 
Console.WriteLine(point.PreviousX) \\ Выведет 0, хотя point там никогда не был

2019-12-04 13:58 UTC, afdenisoff-dev commented on DevFactoryZ.SchemeExpert/Volume/IPoint.cs
> +        double PreviousZ { get; }
Поскольку координаты 0,0,0 - реальны, может, стоит их сделать double?

2019-12-04 13:58 UTC, afdenisoff-dev commented on DevFactoryZ.SchemeExpert/Volume/IPoint.cs
> +        double PreviousZ { get; }
В смысле, Nullable<double>

2019-12-05 07:29 UTC, zykindmitry commented on DevFactoryZ.SchemeExpert/Infrastructure/PointCoordinatesChangedEventArgs.cs
> +namespace System.ComponentModel
Свои классы не принято помещать в системные пространства имен

2019-12-05 07:31 UTC, zykindmitry commented on DevFactoryZ.SchemeExpert/Volume/IPoint.cs
> +        double PreviousZ { get; }
Да это устранит проблему ошибочного состояния, однако они нам все равно не нужны все события, поэтому их в принципе хранить в объекте не имеет смысла

2019-12-06 11:37 UTC, afdenisoff-dev commented on DevFactoryZ.SchemeExpert/Infrastructure/PointCoordinatesChangedEventArgs.cs
> +namespace System.ComponentModel
Тогда надо определиться, где их размещать. 
Предлагаю  все расширения и наследников от системных классов размещать в DevFactoryZ.Extensions. 
Расширения собственных классов проектов - в DevFactoryZ.<Пространство имен проекта>.Extensions.
Или валить все в корневое пространство проекта?
Как считаете?

2019-12-08 06:47 UTC, zykindmitry requested changes

2019-12-08 06:47 UTC, zykindmitry commented on DevFactoryZ.SchemeExpert/Infrastructure/LocationChangedEventArgs.cs
> +namespace System.ComponentModel
Не используем системные пространства имен для своих классов

2019-12-08 06:47 UTC, zykindmitry commented on DevFactoryZ.SchemeExpert/Infrastructure/ILocation.cs
> +    }
Уточните зачем нам еще один интерфейс ?

2019-12-08 06:47 UTC, zykindmitry commented on DevFactoryZ.SchemeExpert/Volume/ILocation.cs
> +        uint Precision { get; }
Precision по отношению к системе это константа или потенциально конфигурационный параметр (или в крайнем случае атрибут всей схемы). У нас не может быть на одной схеме точек с разной точностью определения координат по понятным причинам. Соотв. когда мы получаем запрос на сравнение двух объектов типа ILocation precision является параметром операции сравнения. а не каждой отдельно взятой локации

2019-12-08 06:47 UTC, zykindmitry commented on DevFactoryZ.SchemeExpert/Volume/Location.cs
> +                : X.Equals(compareWith.X, compareWith.Precision) && Y.Equals(compareWith.Y, compareWith.Precision) && Z.Equals(compareWith.Z, compareWith.Precision);
А если Precision нашего объекта отличается от Precision объекта. с которым сравниваем.

2019-12-08 06:47 UTC, zykindmitry commented on DevFactoryZ.SchemeExpert/Volume/Location.cs
> +
Предлагаю для упрощения кода переопределить и ряд операторов. см. https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/operators/operator-overloading

2019-12-08 06:47 UTC, zykindmitry commented on DevFactoryZ.SchemeExpert/Volume/Point.cs
> +        public void MoveTo(double newValueX, double newValueY, double newValueZ, uint newValuePrecision)
newValuePrecision - это значение не изменяется в рамках жизненного цикла

2019-12-08 06:47 UTC, zykindmitry commented on DevFactoryZ.SchemeExpert/Volume/Point.cs
> +            }
Предлагаю упростить используя ?. и ??

var previous = Location;
Location = newLocation ?? throw new ArgumentNullException(...);
if (Location != previous) // учитывая, что мы переопределили оператор ==
{
  OnPointMoved(...)
}

2019-12-08 06:47 UTC, zykindmitry commented on DevFactoryZ.SchemeExpert/Volume/Point.cs
> +                var previous = new Location(Location.X, Location.Y, Location.Z, Location.Precision);
Если MoveTo не был вызван не извне. а из конструктора или метода MoveTo(double, double, double). то мы породим лишний объект. Предлагаю этого не делать. Location - объект иммутабельный и нам нет нужды беспокоиться о модификации извне.

2019-12-11 08:50 UTC, zykindmitry commented on DevFactoryZ.SchemeExpert/Volume/Location.cs
> +            }
Метод CreateByAdding трактует null как нулевой вектор, в этом же методе генерируется исключение. Должно быть какое-то одно поведение. Причем данный вариант более предпочтителен, так как передача null может быть следствием ошибки и попытка трактовать null каким-то образом усложнит отладку (ошибка "вылезет" не там, где ее источник, а где-то неявно потом). Собственно по этой причине передача null в качестве параметра и последующая трактовка не как null - есть антишаблон проектирования.

2019-12-11 08:58 UTC, zykindmitry requested changes

2019-12-11 08:58 UTC, zykindmitry commented on DevFactoryZ.SchemeExpert/Volume/Location.cs
> +            return base.GetHashCode();
Такая реализация Hash-кода не соответствует реализации Equals. У двух Equals = true объектов Hash-коды должны быть одинаковы, в противном случае работа с различными коллекциями типа Dictionary или HashSet будет иметь непредстакуемые результаты.

2019-12-11 08:58 UTC, zykindmitry commented on DevFactoryZ.SchemeExpert/Volume/Point.cs
> +            : this(new Location(x, y, z, precision))
Как мы вчера обсудили такой конструктор точки не должен быть доступен, так как позволяет "пользователю" создать точку с каким угодно precision-ом

2019-12-11 08:58 UTC, zykindmitry commented on DevFactoryZ.SchemeExpert/Volume/Point.cs
> +        public ILocation Location { get; private set; }
Я бы предложил сделать так:
private Location location;
public ILocation Location => location;

тогда в методе MoveTo не потребуется приведение типа

2019-12-12 06:32 UTC, afdenisoff-dev commented on DevFactoryZ.SchemeExpert/Volume/Point.cs
> +        public ILocation Location { get; private set; }
Но тогда приведение потребуется в сеттере Location?

2019-12-12 06:45 UTC, zykindmitry commented on DevFactoryZ.SchemeExpert/Volume/Point.cs
> +        public ILocation Location { get; private set; }
В случае с полем setter-а не нужно в принципе.

2019-12-12 06:46 UTC, zykindmitry commented on DevFactoryZ.SchemeExpert/Volume/Point.cs
> +        public ILocation Location { get; private set; }
ILocation по задумке это не интерфейс повторного использования. Это скорее интерфейс для внешних пользователей, чтобы скрыть от них то, что им не нужно

2019-12-12 07:28 UTC, afdenisoff-dev commented on DevFactoryZ.SchemeExpert/Volume/Point.cs
> +        public ILocation Location { get; private set; }
тогда не работает строка
location = newLocation ?? throw new ArgumentNullException(nameof(newLocation), "Не заданы координаты 3D-точки / вектора.");
Делать location = new Location(...) ? Возвращаемся к предыдущему варианту?

2019-12-12 11:03 UTC, zykindmitry approved these changes

2019-12-13 07:20 UTC, merged